import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { createAuthMiddleware, APIError, getSessionFromCtx } from "better-auth/api";
import { prisma } from "@/lib/prisma";
import { env } from "@/lib/env";
import { SYSTEM_ROLE_IDS } from "@/constants/roles";
import { PERMISSIONS } from "@/constants/permissions";

export const auth = betterAuth({
  database: prismaAdapter(prisma, { provider: "postgresql" }),
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,

  // This system is admin-provisioned (staff/students are created by an Admin from
  // the User Management module), not publicly self-registered — there is no /register
  // page. `disableSignUp` was considered but rejected: it blocks the handler
  // unconditionally, including our own trusted server-side admin calls. Instead the
  // hook below requires the *caller* to already hold an authenticated session with
  // "users.create" before /sign-up/email is allowed to run at all.
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // The only caller of /sign-up/email is an admin creating someone ELSE's
    // account (see the hook below) — auto sign-in would overwrite the
    // admin's own session cookie with the new user's session.
    autoSignIn: false,
  },

  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60 * 24, // refresh once per day of activity
  },

  rateLimit: {
    window: 60,
    max: 100,
    customRules: {
      "/sign-in/email": { window: 60, max: 5 },
    },
  },

  hooks: {
    before: createAuthMiddleware(async (ctx) => {
      if (ctx.path !== "/sign-up/email") return;

      const session = await getSessionFromCtx(ctx);
      if (!session?.user) {
        throw new APIError("UNAUTHORIZED", { message: "Sign-up is admin-only." });
      }

      const role = await prisma.role.findUnique({
        where: { id: session.user.roleId },
        select: { permissions: { select: { permission: { select: { key: true } } } } },
      });
      const permissionKeys = role?.permissions.map((rp) => rp.permission.key) ?? [];
      if (!permissionKeys.includes(PERMISSIONS.users.create)) {
        throw new APIError("FORBIDDEN", { message: "Missing users.create permission." });
      }
    }),
  },

  advanced: {
    database: {
      // Ids are generated by Prisma (@default(cuid())), not by Better Auth.
      generateId: false,
    },
  },

  user: {
    additionalFields: {
      roleId: {
        type: "string",
        input: false, // never settable by the client — assigned/corrected server-side
        defaultValue: SYSTEM_ROLE_IDS.STAFF, // least-privilege safety net; createUser() always overrides this
      },
      status: {
        type: "string",
        input: false,
        defaultValue: "ACTIVE",
      },
      phone: {
        type: "string",
        required: false,
      },
    },
  },
});
